declare const hidden: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
declare const block: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
declare const inlineBlock: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
declare const inline: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
declare const flex: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
declare const inlineFlex: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
declare const grid: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
declare const table: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
declare const tableCaption: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
declare const tableCell: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
declare const tableColumn: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
declare const tableColumnGroup: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
declare const tableFooterGroup: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
declare const tableHeaderGroup: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
declare const tableRowGroup: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
declare const tableRow: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
export { hidden, block, inlineBlock, inline, flex, inlineFlex, grid, table, tableCaption, tableCell, tableColumn, tableColumnGroup, tableFooterGroup, tableHeaderGroup, tableRowGroup, tableRow };
