declare const maxWXs: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
declare const maxWSm: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
declare const maxWMd: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
declare const maxWLg: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
declare const maxWXl: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
declare const maxW2xl: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
declare const maxW3xl: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
declare const maxW4xl: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
declare const maxW5xl: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
declare const maxW6xl: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
declare const maxWFull: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
declare const maxWScreenSm: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
declare const maxWScreenMd: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
declare const maxWScreenLg: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
declare const maxWScreenXl: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
declare const maxWNone: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
export { maxWXs, maxWSm, maxWMd, maxWLg, maxWXl, maxW2xl, maxW3xl, maxW4xl, maxW5xl, maxW6xl, maxWFull, maxWScreenSm, maxWScreenMd, maxWScreenLg, maxWScreenXl, maxWNone };
