declare const textXs: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
declare const textSm: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
declare const textBase: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
declare const textLg: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
declare const textXl: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
declare const text2xl: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
declare const text3xl: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
declare const text4xl: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
declare const text5xl: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
declare const text6xl: (node: import("@isotope/core/lib/node").IsotopeNode<any, import("../../declarations").Context>) => void;
export { textXs, textSm, textBase, textLg, textXl, text2xl, text3xl, text4xl, text5xl, text6xl };
